server:
  port: 8021

spring:
  application:
    name: user-service

  profiles:
    active: local
  liquibase:
        enabled: true
        change-log: classpath:db/changelog.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka