version: '3.8'
services:
  db:
    container_name: parcel-delivery-app-db
    image: postgres:14.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ../../docker-volumes/parcel-delivery-app-db:/var/lib/postgresql/data